name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Test
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test
          yarn build
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.LIFEOMIC_NPM_TOKEN }}
        run: |
          yarn semantic-release
